<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace frontend\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "for_payment_history".
 *
 * @property integer $id
 * @property integer $application_id
 * @property string $razorpay_payment_id
 * @property integer $student_id
 * @property string $student
 * @property integer $course_id
 * @property string $course
 * @property integer $college_id
 * @property string $college
 * @property string $amount
 * @property string $currency
 * @property string $payment_method
 * @property string $payment_type
 * @property integer $payment_date
 * @property integer $status
 * @property integer $created_by
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class ForPaymentHistory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'for_payment_history';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['application_id', 'razorpay_payment_id', 'student_id', 'student', 'course_id', 'course', 'college_id', 'college', 'amount', 'currency', 'payment_type', 'payment_date'], 'required'],
            [['application_id', 'student_id', 'course_id', 'college_id', 'payment_date', 'status'], 'integer'],
            [['amount'], 'number'],
            [['razorpay_payment_id', 'student', 'course', 'college', 'payment_method'], 'string', 'max' => 255],
            [['currency'], 'string', 'max' => 5],
            [['payment_type'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'application_id' => 'Application ID',
            'razorpay_payment_id' => 'Razorpay Payment ID',
            'student_id' => 'Student ID',
            'student' => 'Student',
            'course_id' => 'Course ID',
            'course' => 'Course',
            'college_id' => 'College ID',
            'college' => 'College',
            'amount' => 'Amount',
            'currency' => 'Currency',
            'payment_method' => 'Payment Method',
            'payment_type' => 'Payment Type',
            'payment_date' => 'Payment Date',
            'status' => 'Status',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
        ];
    }




}
