<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "applied_council_student".
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property integer $country
 * @property string $state
 * @property string $city
 * @property integer $college_id
 * @property integer $course_id
 * @property integer $zip_code
 * @property string $additional_message
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\School $college
 * @property \common\models\Course $course
 * @property string $aliasModel
 */
abstract class AppliedCouncilStudent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'applied_council_student';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'email', 'phone', 'country', 'state', 'city', 'college_id', 'course_id', 'zip_code', 'additional_message'], 'required'],
            [['country', 'college_id', 'course_id', 'zip_code'], 'integer'],
            [['name'], 'string', 'max' => 120],
            [['email'], 'string', 'max' => 65],
            [['phone'], 'string', 'max' => 20],
            [['state', 'city'], 'string', 'max' => 125],
            [['additional_message'], 'string', 'max' => 300],
            [['college_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\School::className(), 'targetAttribute' => ['college_id' => 'id']],
            [['course_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Course::className(), 'targetAttribute' => ['course_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'country' => 'Country',
            'state' => 'State',
            'city' => 'City',
            'college_id' => 'College ID',
            'course_id' => 'Course ID',
            'zip_code' => 'Zip Code',
            'additional_message' => 'Additional Message',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCollege()
    {
        return $this->hasOne(\common\models\School::className(), ['id' => 'college_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCourse()
    {
        return $this->hasOne(\common\models\Course::className(), ['id' => 'course_id']);
    }




}
