<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "apply_student".
 *
 * @property integer $id
 * @property string $school_name
 * @property string $course_name
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $comment
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class ApplyStudent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'apply_student';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['school_name','email','phone'], 'required'],
            [['comment'], 'string'],
            [['school_name'], 'string', 'max' => 130],
            [['course_name', 'name', 'email', 'phone'], 'string', 'max' => 120]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'school_name' => 'School Name',
            'course_name' => 'Course Name',
            'name' => 'Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'comment' => 'Comment',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
