<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "course_additional_info".
 *
 * @property integer $id
 * @property integer $clg_id
 * @property integer $course_id
 * @property string $type
 * @property string $info
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class CourseAdditionalInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course_additional_info';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['clg_id', 'course_id'], 'required'],
            [['clg_id', 'course_id'], 'integer'],
            [['type', 'info'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'clg_id' => 'Clg ID',
            'course_id' => 'Course ID',
            'type' => 'Type',
            'info' => 'Info',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
