<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "course".
 *
 * @property integer $id
 * @property integer $college_id
 * @property string $tution_fee
 * @property string $application_fee
 * @property string $name
 * @property integer $discount
 * @property string $tags
 * @property integer $status
 * @property string $comment
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\School $college
 * @property string $aliasModel
 */
abstract class Course extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['college_id', 'name', 'comment'], 'required'],
            [['college_id', 'discount', 'status','recruiter_id'], 'integer'],
            [['tution_fee', 'application_fee'], 'number'],
            [['registeration_fee', 'duration'], 'safe'],
            [['tags', 'comment'], 'string'],
            [['name'], 'string', 'max' => 120],
            [['college_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\School::className(), 'targetAttribute' => ['college_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'college_id' => 'College',
            'tution_fee' => 'Tution Fee',
            'application_fee' => 'Application Fee',
            'name' => 'Name',
            'discount' => 'Discount',
            'tags' => 'Tags',
            'status' => 'Status',
            'comment' => 'Comment',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCollege()
    {
        return $this->hasOne(\common\models\School::className(), ['id' => 'college_id']);
        // return $this->hasOne(\common\models\School::className(), ['id' => 'college_id']);
    }

    public function getSchool()
    {
        return $this->hasOne(\common\models\School::className(), ['id' => 'college_id']);
    }




}
