<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "mou_detail".
 *
 * @property integer $id
 * @property integer $recruiter_id
 * @property string $reference_id
 * @property string $signature_image
 * @property string $mou_agreement_file
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class MouDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mou_detail';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['recruiter_id', 'signature_image'], 'required'],
            [['recruiter_id'], 'integer'],
            [['reference_id', 'signature_image', 'mou_agreement_file'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'recruiter_id' => 'Recruiter ID',
            'reference_id' => 'Reference ID',
            'signature_image' => 'Signature Image',
            'mou_agreement_file' => 'Mou Agreement File',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
