<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "recruiter_commision_history".
 *
 * @property integer $id
 * @property string $application_id
 * @property integer $total_applications
 * @property integer $recruiter_id
 * @property string $amount
 * @property integer $created_at
 * @property integer $created_by
 * @property string $aliasModel
 */
abstract class RecruiterCommisionHistory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'recruiter_commision_history';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['application_id', 'total_applications', 'recruiter_id', 'amount'], 'required'],
            [['total_applications', 'recruiter_id'], 'integer'],
            [['amount'], 'number'],
            [['application_id'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'application_id' => 'Application ID',
            'total_applications' => 'Total Applications',
            'recruiter_id' => 'Recruiter ID',
            'amount' => 'Amount',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
        ];
    }




}
