<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "review".
 *
 * @property integer $id
 * @property integer $info_id
 * @property string $name
 * @property string $email_id
 * @property integer $type
 * @property string $comment
 * @property double $rating
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Review extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'review';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['info_id', 'name', 'email_id', 'type', 'comment', 'rating'], 'required'],
            [['info_id', 'type'], 'integer'],
            [['comment'], 'string'],
            [['rating'], 'number'],
            [['name'], 'string', 'max' => 120],
            [['email_id'], 'string', 'max' => 65]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'info_id' => 'Info ID',
            'name' => 'Name',
            'email_id' => 'Email ID',
            'type' => 'Type',
            'comment' => 'Comment',
            'rating' => 'Rating',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'type' => '0 - school, 1- course',
        ]);
    }




}
