<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "school".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $slug
 * @property string $ref_no
 * @property string $name
 * @property integer $status
 * @property integer $dest_country
 * @property string $cont_fname
 * @property string $cont_last_name
 * @property string $phone_number
 * @property string $cont_email
 * @property string $cont_title
 * @property string $comment
 * @property string $min_price
 * @property string $max_price
 * @property string $avg_price
 * @property integer $show_home
 * @property integer $type
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\Course[] $courses
 * @property string $aliasModel
 */
abstract class School extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'school';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'dest_country', 'cont_fname', 'cont_last_name', 'cont_email', 'cont_title'], 'required'],
            [['user_id', 'status', 'dest_country', 'show_home', 'type'], 'integer'],
            [['comment'], 'string'],
            [['slug'], 'string', 'max' => 200],
            [['ref_no'], 'string', 'max' => 20],
            [['name'], 'string', 'max' => 220],
            [['cont_fname', 'cont_last_name'], 'string', 'max' => 120],
            [['phone_number'], 'string', 'max' => 15],
            [['cont_email'], 'string', 'max' => 60],
            [['cont_title'], 'string', 'max' => 240],
            [['cont_email'], 'unique'],
            [['min_price', 'max_price', 'avg_price'], 'string', 'max' => 25]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'slug' => 'Slug',
            'ref_no' => 'Ref No',
            'name' => 'Name',
            'status' => 'Status',
            'dest_country' => 'Dest Country',
            'cont_fname' => 'Cont Fname',
            'cont_last_name' => 'Cont Last Name',
            'phone_number' => 'Phone Number',
            'cont_email' => 'Cont Email',
            'cont_title' => 'Cont Title',
            'comment' => 'Comment',
            'min_price' => 'Min Price',
            'max_price' => 'Max Price',
            'avg_price' => 'Avg Price',
            'show_home' => 'Show Home',
            'type' => 'Type',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCourses()
    {
        return $this->hasMany(\common\models\Course::className(), ['college_id' => 'id']);
    }




}
