<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "setting".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $keywords
 * @property string $logo
 * @property string $analytics
 * @property string $phone
 * @property string $email
 * @property string $address
 * @property string $copyright
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Setting extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'setting';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['description', 'keywords', 'analytics', 'address', 'copyright'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['logo'], 'string', 'max' => 120],
            [['phone'], 'string', 'max' => 14],
            [['email'], 'string', 'max' => 65]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'keywords' => 'Keywords',
            'logo' => 'Logo',
            'analytics' => 'Analytics',
            'phone' => 'Phone',
            'email' => 'Email',
            'address' => 'Address',
            'copyright' => 'Copyright',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
