<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "student_school_applied".
 *
 * @property integer $id
 * @property integer $student_id
 * @property integer $college_id
 * @property integer $course_id
 * @property integer $recruiter_id
 * @property string $application_fee
 * @property integer $application_fee_status
 * @property string $visa_fee
 * @property integer $visa_fee_status
 * @property integer $payment_date
 * @property integer $pay_status
 * @property string $commission_amount
 * @property integer $created_at
 * @property integer $created_by
 * @property string $aliasModel
 */
abstract class StudentCollegeApplied extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_school_applied';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
                'updatedByAttribute' => false,
            ],
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_id', 'college_id', 'course_id', 'recruiter_id'], 'required'],
            [['student_id', 'college_id', 'course_id', 'recruiter_id', 'application_fee_status', 'visa_fee_status', 'payment_date', 'pay_status'], 'integer'],
            [['application_fee', 'visa_fee', 'commission_amount'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'student_id' => 'Student ID',
            'college_id' => 'College ID',
            'course_id' => 'Course ID',
            'recruiter_id' => 'Recruiter ID',
            'application_fee' => 'Application Fee',
            'application_fee_status' => 'Application Fee Status',
            'visa_fee' => 'Visa Fee',
            'visa_fee_status' => 'Visa Fee Status',
            'payment_date' => 'Payment Date',
            'pay_status' => 'Pay Status',
            'commission_amount' => 'Commission Amount',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
        ];
    }




}
