<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers\base;
use Yii;
use common\models\School;
use backend\models\SchoolSearch;
use common\models\User;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;
use yii\web\UploadedFile;
use common\models\ExcelUpload;
use common\models\UploadForm;
/**
* SchoolController implements the CRUD actions for School model.
*/
class SchoolController extends Controller
{


/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all School models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new SchoolSearch;
    $dataProvider = $searchModel->search($_GET);

    Tabs::clearLocalStorage();
    
    Url::remember();
    \Yii::$app->session['__crudReturnUrl'] = null;
    if( \Yii::$app->user->identity->type==5){
      return $this->render('index_rm', [
    'dataProvider' => $dataProvider,
        'searchModel' => $searchModel,
    ]);
    }else{
    return $this->render('index', [
    'dataProvider' => $dataProvider,
        'searchModel' => $searchModel,
    ]);
    }
}


public function actionDownloaddocument($id,$c)
    {
        //echo $c;die;
        $model =  \common\models\SchoolImage::findOne($id);
        $file=$model->name;
        $mainpath = Yii::getAlias('@webroot/');
        $convertPath = str_ireplace('/backend/web', '/frontend/web',$mainpath);
        $mainroot=$convertPath.'uploads/'.$c;
        if (file_exists($mainroot)) {
            return Yii::$app->response->sendFile($mainroot);
        } else {
            throw new \yii\web\NotFoundHttpException("{$file} is not found!");
        }
    }
public function actionUpdateimage($id)
    {
        $checkmodel = \common\models\SchoolImage::find()->where(['school_id'=>$id])->One();
        if($checkmodel){
            $model = $checkmodel;
            $model1 =  \common\models\SchoolImage::find()->where(['school_id'=>$id])->One();
        }else{
            $model=new \common\models\SchoolImage();
        }

        if ($model->load($_POST)) {

            if(!empty(UploadedFile::getInstance($model, 'name'))){
                
                $modelUploadForm = new UploadForm();
                $modelUploadForm->name = UploadedFile::getInstance($model, 'name');
                    if(!empty($modelUploadForm->name->extension)){
                        
                        $image_name=uniqid() . '.' . $modelUploadForm->name->extension;
                        $model->name =  $image_name;
                        $model->school_id=$id;
                        $mainpath = Yii::getAlias('@webroot/');
                        $convertPath = str_ireplace('/backend/web', '/frontend/web',$mainpath);
                        $modelUploadForm->name->saveAs($convertPath.'uploads/' . $image_name);
                    }else{
                        $model->school_id=$id;
                        $model->name=$model1->name;
                    }
                }else{
                    $model->name=$model1->name;
                }
                
                if(!$model->save(false)){
                  print_r($model->getErrors());die;
                }else{
                    
                     return $this->redirect(['index']);
                }
               
            } else {
            return $this->render('update_image', [
            'model' => $model,
            ]);
            }
    }


public function actionUploadexcel()
    {
        $searchModel  = new SchoolSearch;
        $dataProvider = $searchModel->search($_GET);
        Tabs::clearLocalStorage();
        Url::remember();
        \Yii::$app->session['__crudReturnUrl'] = null;
        return $this->render('upload_excel', [
        'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    public function actionCollegeuploadexcel(){
        $model=new ExcelUpload();
        if(!empty($_FILES['file']['name'])){
            $filename = $_FILES['file']['name'];
            $filetmpname = $_FILES['file']['tmp_name'];
            $result = $this->uploadFile($filename, $filetmpname);
            if($result['status'] === false){
                Yii::$app->session->setFlash('error', $result['message']);
                return $this->redirect(['uploadexcel']);
                } else {
                    $model->file=$result['filename'];
                    $model->date_created=date('Y-m-d');
                    $model->save(false);
                }
         }
         $file_name = Yii::getAlias('@webroot/uploads/excel/'.$model->file);
        // $file_name =  $_FILES['file']['name'];
        $row = 1;
        if (($handle = fopen($file_name, "r")) !== FALSE) {
            while (($data = fgetcsv($handle,1000, ",")) !== FALSE) {
                //   echo '<pre>';print_r($data);continue;
                $num = 4;
                $row++;
               if($row != 2 && $row < 2473)
                { 
                     //echo '<pre>';print_r($data);
                    $School  = new School();
                    $School->user_id=trim($data[0]); 
                    $School->slug=trim($data[1]); 
                    $School->ref_no=trim($data[2]);  
                    $School->name=trim($data[3]);  
                    $School->campus=trim($data[4]);  
                    $School->description=trim($data[5]);  
                    $School->status=trim($data[6]);
                    $School->dest_country=trim($data[7]);  
                    $School->cont_fname=trim($data[8]);  
                    $School->cont_last_name=trim($data[9]); 
                    $School->phone_number=trim($data[10]);  
                    $School->cont_email=trim($data[11]); 
                    $School->cont_title=trim($data[12]);  
                    $School->comment=trim($data[13]);  
                    $School->min_price=trim($data[14]);  
                    $School->max_price=trim($data[15]);  
                    $School->avg_price=trim($data[16]); 
                    $School->show_home=trim($data[17]); 
                    $School->type=trim($data[18]); 
                    $School->intake=trim($data[19]); 
                    $School->entry_requirment=trim($data[20]); 
                    $School->level_of_education=trim($data[21]); 
                    $School->start_date=date('Y-m-d',strtotime(trim($data[22])));
                    $School->accomodation_fee=trim($data[23]); 
                    $School->submission_deadlines=trim($data[24]); 
                    $School->average_processing_time=trim($data[25]); 
                    $School->cash_deposit=trim($data[26]); 
                    $School->los_deposit=trim($data[27]); 
                    $School->minimum_deposit=trim($data[28]); 
                    $School->visa_fee=trim($data[29]); 
                    $School->servis_fee=trim($data[30]); 
                    $School->save(false);
                    
                 }

            }
            Yii::$app->session->setFlash('success', "Data uploaded successfully.");
            return $this->redirect(['index']);
        }
    }

    public function uploadFile($filename, $tmpname) {

        $output = [];
        $upload_dir = Yii::getAlias('@webroot').'/uploads/excel/';        
        
        if(!empty($filename)){

            $target_file = $upload_dir . basename($filename);
            $imageFileType = strtolower(pathinfo($target_file,PATHINFO_EXTENSION));
            
            if($imageFileType != "csv") {               
                return $output = [
                    'status' => false,
                    'message' => "Sorry, only csv files are allowed."
                ];
            }
           
           /* if (file_exists($target_file)) {                
                return $output = [
                    'status' => false,
                    'message' => "Sorry, file already exists."
                ];
            }*/

            if (move_uploaded_file($tmpname, $target_file)) {
                return $output = [
                    'status' => true,
                    'message' => "Hurray, File uploaded successfully.",
                    'filename' => $filename
                ];
            } else {
                return $output = [
                    'status' => false,
                    'message' => "Sorry, File can not be uploaded."
                ];
            }
        } else {
            return $output = [
                'status' => false,
                'message' => "Sorry, File not found."
            ];
        } 
    }

/**
* Displays a single School model.
* @param integer $id
*
* @return mixed
*/
    public function actionView($id)
    {
        \Yii::$app->session['__crudReturnUrl'] = Url::previous();
        Url::remember();
        Tabs::rememberActiveState();

        return $this->render('view', [
        'model' => $this->findModel($id),
        ]);
    }

    public function actionApprove($id){

        $model=  $this->findModel($id);
        $password="23#28&5";
        $user_info= User::find()->where(['id'=>$model->user_id])->one();
        if(!empty($user_info)){
            $model->status=1;
            $model->save(false);
            $mail = Yii::$app->mailer->compose('@common/mail/institution/institute-accept', ['user' => $user_info, 'school' => $model]) 
                        ->setFrom('noreply@universitybureau.com')
                        ->setTo($user_info->email)
                        // ->setTo('salman.u360@gmail.com')
                        ->setSubject('Congratulations...!! Your request has been approved by Admin.')
                        ->send(); 
           
            \Yii::$app->getSession()->addFlash('success', "School approved successfully and email has been sent to school email");
            return $this->redirect(['index']);
        }
        $user = new User(); 
        $user->username =  $model->cont_email;
        $user->email =  $model->cont_email;
        $user->password_hash = \Yii::$app->security->generatePasswordHash($password);
        $user->type =  USER::TYPE_USER_SCHOOL;
        $user->auth_key = uniqid(); 
        $user->password = $password;
        $user->confirm_password= $password;
        $user->status=USER::STATUS_ACTIVE;
        if($user->save()){
            $model->agree=true;
            $model->status=1;
            $model->user_id=$user->id;
            $model->save(false);
            $mail = Yii::$app->mailer->compose('@common/mail/institution/institute-accept', ['user' => $user, 'school' => $model]) 
                        ->setFrom('noreply@universitybureau.com')
                        ->setTo($user->email)
                        // ->setTo('salman.u360@gmail.com')
                        // ->setTo('ibpahulpreetsingh90@gmail.com')
                        ->setSubject('Congratulations...!! Your request has been approved by Admin.')
                        ->send(); 
           
            \Yii::$app->getSession()->addFlash('success', "School approved successfully and email has been sent to school email");
            return $this->redirect(['index']);
        }else{
            print_r($user->getErrors());
            print_r($model->getErrors());die;
        }

    }

    public function actionDisapprove($id){
        $model=  $this->findModel($id);
        $model->status=2;
        $model->save(false);
        $mail = Yii::$app->mailer->compose('@common/mail/institution/institute-reject') 
        ->setFrom('noreply@universitybureau.com')
        ->setTo([$model->cont_email])
        // ->setTo('salman.u360@gmail.com')
        ->setSubject('Sorry...!! Your request has been Dissapproved by Admin.')
        ->send(); 
        \Yii::$app->getSession()->addFlash('success', "School disapprove successfully");
        return $this->redirect(['index']);
    }

/**
* Creates a new School model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
    public function actionCreate()
    {
        $model = new School;

        try {
        if ($model->load($_POST)) {
            $model->comission=$_POST['School']['comission'];
            $model->province=$_POST['School']['province'];
            $model->save();
        return $this->redirect(['view', 'id' => $model->id]);
        } elseif (!\Yii::$app->request->isPost) {
        $model->load($_GET);
        }
        } catch (\Exception $e) {
        $msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
        $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

/**
* Updates an existing School model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id
* @return mixed
*/
public function actionUpdate($id)
{
$model = $this->findModel($id);

if ($model->load($_POST)) {
    $model->comission=$_POST['School']['comission'];
    $model->province=$_POST['School']['province'];
     $model->save();
    return $this->redirect(['view', 'id' => $model->id]);
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing School model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $id
* @return mixed
*/
public function actionDelete($id)
{
try {
$this->findModel($id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

/**
* Finds the School model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $id
* @return School the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($id)
{
if (($model = School::findOne($id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
