<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
    * @var frontend\models\CourseSearch $searchModel
*/

$this->title = Yii::t('models', 'Course');
$this->params['breadcrumbs'][] = $this->title;

if (isset($actionColumnTemplates)) {
$actionColumnTemplate = implode(' ', $actionColumnTemplates);
    $actionColumnTemplateString = $actionColumnTemplate;
} else {
Yii::$app->view->params['pageButtons'] = Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']);
    $actionColumnTemplateString = "{view} {apply}";
}
$actionColumnTemplateString = '<div class="action-buttons">'.$actionColumnTemplateString.'</div>';
?>
<div class="giiant-crud course-index">

  <div class="row">
                     <?php
                     $st=Yii::$app->session->getFlash('success');
                   
                     if(!empty($st)){ ?>
                     <div class="alert alert-success">
                     <p > <b> <?=  $st; ?></b></p>

                     
                    <?php }
                     
                     ?>
</div>

    <h1>
        <?= Yii::t('models.plural', 'Course') ?>
        <small>
            <?= Yii::t('cruds', 'List') ?>
        </small>
    </h1>

    <?php
           echo $this->render('_search', ['model' =>$searchModel]);
        ?>

    
    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

    
    <div class="clearfix crud-navigation">
        <!-- <div class="pull-left">
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
        </div> -->

      

    <hr />

    <div class="table-responsive">
        <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'pager' => [
        'class' => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel' => 'Last',
        ],
                 //   'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
        'headerRowOptions' => ['class'=>'x'],
        'columns' => [
                [
            'class' => 'yii\grid\ActionColumn',
            'template' => $actionColumnTemplateString,
            'buttons' => [
                'view' => function ($url, $model, $key) {
                     return Html::a('<i class="fa fa-eye margin-r-5"></i>'." View", $url, ['class'=>'btn btn-info btn-xs','title'=>"View"]);
                },
                 'apply' => function ($url, $model, $key) {
                  return Html::a('<i class="fa fa-thumbs-up margin-r-5"></i>'." apply",['/student/course/apply', 'course_id' =>$model->id,'school_id'=>$model->college_id], ['class'=>'btn btn-primary  btn-xs','title'=>"apply"]);

                   // return "<button class='btn btn-info btn-xs'  onclick='applyScourse($model->id,$model->college_id)'><i class='fa fa-thumbs-up margin-r-5'></i> Apply</button>";


                }
            ],
            'urlCreator' => function($action, $model, $key, $index) {
                // using the column name as key, not mapping to 'id' like the standard generator
                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                $params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
                return Url::toRoute($params);
            },
            'contentOptions' => ['nowrap'=>'nowrap']
        ],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
			[
			    'class' => yii\grid\DataColumn::className(),
			    'attribute' => 'college_id',
                'label' => 'College Name',
			    'value' => function ($model) {
                    return $model->college->name;
			        // if ($rel = $model->college) {
			        //     return Html::a($rel->name, ['college/view', 'id' => $rel->id,], ['data-pjax' => 0]);
			        // } else {
			        //     return '';
			        // }
			    },
			    'format' => 'raw',
			],

            [
                'class' => yii\grid\DataColumn::className(),
                'attribute' => 'name',
                'label' => 'Course Name',
                'value' => function ($model) {
                    return $model->name;
                    // if ($rel = $model->college) {
                    //     return Html::a($rel->name, ['college/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                    // } else {
                    //     return '';
                    // }
                },
                'format' => 'raw',
            ],
			//'name',
			'comment:ntext',
			//'discount',
			//'status',
			'tution_fee',
			'application_fee',
			/*'tags:ntext',*/
                ]
        ]); ?>
    </div>

</div>


<?php \yii\widgets\Pjax::end() ?>


<div id="myModal_course" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Apply Course !!</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="row">
              <div class="col-sm-4">
                  Add Description
              </div>
              <div class="col-sm-8">
                  <textarea id="add_comment" cols="30" rows="10"></textarea>
              </div>
              <input type="hidden" id="school_id">
              <input type="hidden" id="course_id">
        </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
         <button type="button" class="btn btn-info" >Submit</button>
      </div>
    </div>

  </div>